In [127]:
input_file = "/Users/SteffenPlunder/Documents/Workspace/large_datasets/takafumi/epiblast/wildtype/rosette_cluster_info_s8_v100_20251201.csv"
output_file = "/Users/SteffenPlunder/Documents/Workspace/large_datasets/takafumi/epiblast/wildtype/rosette_cluster_info_s8_v100_20251201_rotated.csv"

data_dir = "/Users/SteffenPlunder/Documents/Workspace/large_datasets/takafumi/epiblast/wildtype/"

In [128]:
import pandas as pd
import numpy as np
import re 
import os
from os.path import join, exists, basename, dirname
from glob import glob
import toml

def get_last_number(s):
    match = re.search(r'(\d+)$', s)
    if match:
        return int(match.group(1))
    else:
        raise ValueError(f"No ending number found in string: {s}")

pts_df = pd.read_csv(input_file)
pts_df["cluster_number"] = [get_last_number(cluster_id) for cluster_id in pts_df["cluster_id"]]
pts_df

cluster_id                       image_id  \
0           epi40_230527_E500_1-4_cluster1          epi40_230527_E500_1-4   
1           epi40_230601_E500_1-6_cluster1          epi40_230601_E500_1-6   
2           epi40_230601_E500_2-3_cluster1          epi40_230601_E500_2-3   
3           epi40_230601_E500_2-3_cluster2          epi40_230601_E500_2-3   
4           epi40_230601_E500_2-6_cluster1          epi40_230601_E500_2-6   
..                                     ...                            ...   
65  epi90_230914_E525_4-7_nolumen_cluster3  epi90_230914_E525_4-7_nolumen   
66          epi90_230914_E525_5-3_cluster1          epi90_230914_E525_5-3   
67          epi90_230914_E525_5-3_cluster2          epi90_230914_E525_5-3   
68          epi90_230914_E525_5-3_cluster3          epi90_230914_E525_5-3   
69          epi90_230914_E525_5-3_cluster4          epi90_230914_E525_5-3   

    stage                embryo_id  n_voxels  max_score  mean_score  \
0   epi40          230527_E500_1-4       668          9       8.250   
1   epi40          230601_E500_1-6       497          8       8.000   
2   epi40          230601_E500_2-3       306          9       8.167   
3   epi40          230601_E500_2-3      2601         11       8.796   
4   epi40          230601_E500_2-6      1305         10       8.139   
..    ...                      ...       ...        ...         ...   
65  epi90  230914_E525_4-7_nolumen       253          8       8.000   
66  epi90          230914_E525_5-3       149          8       8.000   
67  epi90          230914_E525_5-3       647          9       8.009   
68  epi90          230914_E525_5-3      1832         10       8.794   
69  epi90          230914_E525_5-3       103          8       8.000   

    n_voxels_score9  n_voxels_score10  n_voxels_score11  ...  z_max  z_span  \
0               167                 0                 0  ...    209      14   
1                 0                 0                 0  ...    247       7   
2                51                 0                 0  ...    167      12   
3               789               510                87  ...    199      16   
4               179                 1                 0  ...    200      22   
..              ...               ...               ...  ...    ...     ...   
65                0                 0                 0  ...    350      13   
66                0                 0                 0  ...    194       7   
67                6                 0                 0  ...    242       9   
68              702               376                 0  ...    246      12   
69                0                 0                 0  ...    242       4   

    centroid_z_um  centroid_y_um  centroid_x_um  volume_um3  \
0           32.84          62.02          55.83        2.90   
1           39.83          50.02          53.79        2.16   
2           26.20          66.81          51.08        1.33   
3           31.07          54.15          62.25       11.31   
4           30.94          71.59          66.85        5.67   
..            ...            ...            ...         ...   
65          56.14          37.83          62.59        1.10   
66          31.12          53.59          53.34        0.65   
67          38.90          44.59          41.33        2.81   
68          39.17          43.72          59.13        7.96   
69          39.31          46.28          57.85        0.45   

    distance_to_tissue_centroid_um  n_cells_involved  \
0                            10.42                10   
1                             9.07                 8   
2                             9.28                10   
3                            10.69                11   
4                            13.43                12   
..                             ...               ...   
65                           17.92                 8   
66                           11.88                 8   
67                           18.12          

In [129]:
embryo_id_to_folder = {}
for folder in glob(join(data_dir, "epi*", "*")):
    image_id = basename(folder)
    embryo_id_to_folder[image_id] = folder

embryo_id_to_folder

{'230527_E500_1-3': '/Users/SteffenPlunder/Documents/Workspace/large_datasets/takafumi/epiblast/wildtype/epi65/230527_E500_1-3',
 '230601_E500_1-3': '/Users/SteffenPlunder/Documents/Workspace/large_datasets/takafumi/epiblast/wildtype/epi65/230601_E500_1-3',
 '230601_E500_1-2': '/Users/SteffenPlunder/Documents/Workspace/large_datasets/takafumi/epiblast/wildtype/epi65/230601_E500_1-2',
 '230527_E500_1-2': '/Users/SteffenPlunder/Documents/Workspace/large_datasets/takafumi/epiblast/wildtype/epi65/230527_E500_1-2',
 '230622_E475_3-1': '/Users/SteffenPlunder/Documents/Workspace/large_datasets/takafumi/epiblast/wildtype/epi65/230622_E475_3-1',
 '230914_E525_5-2': '/Users/SteffenPlunder/Documents/Workspace/large_datasets/takafumi/epiblast/wildtype/epi65/230914_E525_5-2',
 '230601_E500_2-2': '/Users/SteffenPlunder/Documents/Workspace/large_datasets/takafumi/epiblast/wildtype/epi65/230601_E500_2-2',
 '230914_E525_4-6': '/Users/SteffenPlunder/Documents/Workspace/large_datasets/takafumi/epiblast/w

In [130]:
def backrotate_points(rotated_pts, R, offset, calibration, pixel_size, physical):
    """Rotate points into embryo coordinate frame."""
    factor = pixel_size[0] / calibration  # scaling between original voxel size and downscaled/rotated image voxel size

    pts = rotated_pts * factor * (1/calibration if physical else 1.0)
    pts = (R.T @ pts) + offset
    pts *= (calibration if physical else 1.0)
    return pts

In [167]:
def rotate_points(pts, R, offset, calibration, pixel_size, physical):
    """Rotate points into rotated coordinate frame."""
    factor = pixel_size[0] / calibration  # scaling between original voxel size and downscaled/rotated image voxel size

    rotated_pts = (R @ (pts.T - offset)).T
    rotated_pts /= factor * (1/calibration if physical else 1.0)
    return rotated_pts

In [168]:
# Coordinates are in order: ZYX

In [ ]:
# axis-0: Z
# axis-1: Y
# axis-2: X

for (index, row) in pts_df.iterrows():
    embryo_id = row["embryo_id"]

    # find image folder:
    image_folder = embryo_id_to_folder[image_id]

    rot_data_fn = join(image_folder, "snakemake", "rotated", "rotation_metadata.toml")
    rot_data = toml.load(rot_data_fn)

    R_image_to_embryo = np.array(rot_data["R_image_to_embryo"])
    offset = np.array(rot_data["offset"])
    calibration = 0.1632
    pixel_size = np.array(rot_data["pixel_size"])

    pts_img_coords = np.array([row["centroid_z"], row["centroid_y"], row["centroid_x"]])
    pts_phys_coords = np.array([row["centroid_z_um"], row["centroid_y_um"], row["centroid_x_um"]])
    
    pts_backrotated_img = rotate_points(pts_img_coords, R_image_to_embryo, offset, calibration, pixel_size, physical=False)
    pts_backrotated_phys = rotate_points(pts_phys_coords, R_image_to_embryo, offset, calibration, pixel_size, physical=True)

    pts_df.at[index, "centroid_x_rotated"] = pts_backrotated_img[2]
    pts_df.at[index, "centroid_y_rotated"] = pts_backrotated_img[1]
    pts_df.at[index, "centroid_z_rotated"] = pts_backrotated_img[0]

    pts_df.at[index, "centroid_x_um_rotated"] = pts_backrotated_phys[2]
    pts_df.at[index, "centroid_y_um_rotated"] = pts_backrotated_phys[1]
    pts_df.at[index, "centroid_z_um_rotated"] = pts_backrotated_phys[0]


#groupby embryo_id and write output files per embryo
for embryo_id, group in pts_df.groupby("embryo_id"):
    image_folder = embryo_id_to_folder[embryo_id]
    output_fn = join(image_folder, "snakemake", "rotated", f"rosette_cluster_centroids.csv")
    os.makedirs(dirname(output_fn), exist_ok=True)
    local_df = group.loc[:,["cluster_number", 
                            "centroid_x_rotated", 
                            "centroid_y_rotated", 
                            "centroid_z_rotated"]]
    # rename columns to index, axis-0, axis-1, axis-2
    local_df = local_df.rename(columns={
        "centroid_x_rotated": "axis-2",
        "centroid_y_rotated": "axis-1",
        "centroid_z_rotated": "axis-0",
        "cluster_number": "index"
    })
    # reorder columns
    local_df = local_df.loc[:,["index", "axis-0", "axis-1", "axis-2"]]
    local_df.to_csv(output_fn, index=False) 

    # also write original files (which were rotated)
    output_fn_orig = join(image_folder, "snakemake", "original", f"rosette_cluster_centroids.csv")
    os.makedirs(dirname(output_fn_orig), exist_ok=True)
    local_df_orig = group.loc[:,["cluster_number", "centroid_x", "centroid_y", "centroid_z"]]
    # rename columns to index, axis-0, axis-1, axis-2
    local_df_orig = local_df_orig.rename(columns={
        "centroid_x": "axis-2",
        "centroid_y": "axis-1",
        "centroid_z": "axis-0",
        "cluster_number": "index"
    })
    # reorder columns
    local_df_orig = local_df_orig.loc[:,["index", "axis-0", "axis-1", "axis-2"]]
    local_df_orig.to_csv(output_fn_orig, index=False)



# pts_df.to_csv(output_file, index=False)

[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 301.59545125 980.78533346]
[619.35588698 30

In [170]:
pts_df

cluster_id                       image_id  \
0           epi40_230527_E500_1-4_cluster1          epi40_230527_E500_1-4   
1           epi40_230601_E500_1-6_cluster1          epi40_230601_E500_1-6   
2           epi40_230601_E500_2-3_cluster1          epi40_230601_E500_2-3   
3           epi40_230601_E500_2-3_cluster2          epi40_230601_E500_2-3   
4           epi40_230601_E500_2-6_cluster1          epi40_230601_E500_2-6   
..                                     ...                            ...   
65  epi90_230914_E525_4-7_nolumen_cluster3  epi90_230914_E525_4-7_nolumen   
66          epi90_230914_E525_5-3_cluster1          epi90_230914_E525_5-3   
67          epi90_230914_E525_5-3_cluster2          epi90_230914_E525_5-3   
68          epi90_230914_E525_5-3_cluster3          epi90_230914_E525_5-3   
69          epi90_230914_E525_5-3_cluster4          epi90_230914_E525_5-3   

    stage                embryo_id  n_voxels  max_score  mean_score  \
0   epi40          230527_E500_1-4       668          9       8.250   
1   epi40          230601_E500_1-6       497          8       8.000   
2   epi40          230601_E500_2-3       306          9       8.167   
3   epi40          230601_E500_2-3      2601         11       8.796   
4   epi40          230601_E500_2-6      1305         10       8.139   
..    ...                      ...       ...        ...         ...   
65  epi90  230914_E525_4-7_nolumen       253          8       8.000   
66  epi90          230914_E525_5-3       149          8       8.000   
67  epi90          230914_E525_5-3       647          9       8.009   
68  epi90          230914_E525_5-3      1832         10       8.794   
69  epi90          230914_E525_5-3       103          8       8.000   

    n_voxels_score9  n_voxels_score10  n_voxels_score11  ...  \
0               167                 0                 0  ...   
1                 0                 0                 0  ...   
2                51                 0                 0  ...   
3               789               510                87  ...   
4               179                 1                 0  ...   
..              ...               ...               ...  ...   
65                0                 0                 0  ...   
66                0                 0                 0  ...   
67                6                 0                 0  ...   
68              702               376                 0  ...   
69                0                 0                 0  ...   

    distance_to_tissue_centroid_um  n_cells_involved  \
0                            10.42                10   
1                             9.07                 8   
2                             9.28                10   
3                            10.69                11   
4                            13.43                12   
..                             ...               ...   
65                           17.92                 8   
66                           11.88                 8   
67                           18.12                 9   
68                           22.12                10   
69                           19.33                 8   

                                             cell_ids  cluster_number  \
0             262,270,373,442,542,652,796,839,846,883               1   
1                   649,683,754,755,792,974,1032,1050               1   
2                 70,78,79,97,105,508,511,701,729,737               1   
3          87,330,508,545,596,641,729,792,799,818,819               2   
4   193,276,430,552,607,636,646,737,962,985,1030,1034               1   
..                                                ...             ...   
65            2003,2165,2359,2417,2445,2471,2475,2523               3   
66                    215,233,349,397,592,608,659,696               1   
67                423,489,592,627,653,804,816,822,849               2   
68            349,373,494,496,628,644,827,833,861,876               3   
69       

In [171]:
# test
import napari
import imageio.v3

select_embryo_id, embryo_folder = list(embryo_id_to_folder.items())[1]
select_embryo_id, embryo_folder

('230601_E500_1-3',
 '/Users/SteffenPlunder/Documents/Workspace/large_datasets/takafumi/epiblast/wildtype/epi65/230601_E500_1-3')

In [172]:
# get binned file
binned_image_fn = join(embryo_folder, "snakemake", "rotated", "rotated_composite_ch2.tif")
binned_image = imageio.v3.imread(binned_image_fn)
binned_image.shape

# get coordinates
cluster_pts_fn = join(embryo_folder, "snakemake", "rotated", f"rosette_cluster_centroids.csv")
cluster_pts_df = pd.read_csv(cluster_pts_fn)
cluster_pts_df

index      axis-0      axis-1      axis-2
0      1  208.755894  224.623181  239.901860
1      2  160.133262  226.635959  231.276559
2      3  137.244209  245.691846  223.934936

In [173]:
if "viewer" not in locals():
    viewer = napari.Viewer()

viewer.layers.clear()

viewer.add_image(binned_image, name=f"Binned image {select_embryo_id}")
viewer.add_points(cluster_pts_df.loc[:,["axis-2", "axis-1", "axis-0"]].values, size=10, face_color="red", name="Backrotated rosette centroids")

<Points layer 'Backrotated rosette centroids' at 0x35e1ba5a0>

In [147]:
# get binned file

binned_image_fn = glob(join(embryo_folder, "Binned*.tif"))[0]
binned_image = imageio.v3.imread(binned_image_fn)
binned_image.shape

# get coordinates
cluster_pts_fn = join(embryo_folder, "snakemake", "original", f"rosette_cluster_centroids.csv")
cluster_pts_df = pd.read_csv(cluster_pts_fn)
cluster_pts_df

index  axis-0  axis-1  axis-2
0      1   156.5   354.1   356.8
1      2   250.6   324.0   359.9
2      3   305.7   332.2   334.2

In [148]:
if "viewer" not in locals():
    viewer = napari.Viewer()

viewer.layers.clear()

# 012
# 021
# 102
# 120
# 201
# 210

viewer.add_image(binned_image[:,1,:,:], name=f"Binned image {select_embryo_id}")
viewer.add_points(cluster_pts_df.loc[:,["axis-0", "axis-1", "axis-2"]].values, size=5, face_color="red", name="Original rosette centroids")

<Points layer 'Original rosette centroids' at 0x319a07e30>